# cmake/android/toolchain.cmake
#
# Wrapper toolchain for Android builds.
#
# Resolves the Android SDK path in priority order:
#   1. sdk.dir / ndk.dir already in android/local.properties
#   2. ANDROID_HOME environment variable
#   3. Well-known Android Studio installation paths (Windows / macOS / Linux)
#
# If local.properties is missing or incomplete it is generated automatically
# so subsequent Gradle invocations (e.g. the `apk` CMake target) need no
# manual setup — matching the zero-config experience of Flutter.
#
# VCPKG_HOST_TRIPLET must be set by the calling preset via host preset
# inheritance (host-x64-linux or host-x64-windows).
#
# After resolving the NDK, chains into vcpkg's buildsystem toolchain.

set(_AWEN_NDK_VERSION "29.0.14206865")
set(_LOCAL_PROPS "${CMAKE_CURRENT_LIST_DIR}/../../android/local.properties")

# ── Helper: normalise backslashes from Windows registry / env paths ───────────
macro(_awen_normalise_path _var)
    string(REPLACE "\\\\" "/" ${_var} "${${_var}}")
    string(REPLACE "\\" "/" ${_var} "${${_var}}")
endmacro()

# ── 1. Read existing local.properties ────────────────────────────────────────
if(EXISTS "${_LOCAL_PROPS}")
    file(STRINGS "${_LOCAL_PROPS}" _PROPS)

    foreach(_LINE IN LISTS _PROPS)
        if(_LINE MATCHES "^sdk\\.dir=(.+)$" AND NOT _SDK_DIR)
            set(_SDK_DIR "${CMAKE_MATCH_1}")
            _awen_normalise_path(_SDK_DIR)
        endif()
        if(_LINE MATCHES "^ndk\\.dir=(.+)$" AND NOT _NDK_HOME)
            set(_NDK_HOME "${CMAKE_MATCH_1}")
            _awen_normalise_path(_NDK_HOME)
        endif()
    endforeach()
endif()

# ── 2. Discover SDK if not yet known ─────────────────────────────────────────
if(NOT _SDK_DIR)
    # ANDROID_HOME env var (set by Android Studio on all platforms)
    if(DEFINED ENV{ANDROID_HOME} AND EXISTS "$ENV{ANDROID_HOME}")
        set(_SDK_DIR "$ENV{ANDROID_HOME}")
    # Windows: %LOCALAPPDATA%\Android\Sdk
    elseif(CMAKE_HOST_WIN32 AND DEFINED ENV{LOCALAPPDATA}
            AND EXISTS "$ENV{LOCALAPPDATA}/Android/Sdk")
        set(_SDK_DIR "$ENV{LOCALAPPDATA}/Android/Sdk")
    # macOS: ~/Library/Android/sdk
    elseif(APPLE AND DEFINED ENV{HOME}
            AND EXISTS "$ENV{HOME}/Library/Android/sdk")
        set(_SDK_DIR "$ENV{HOME}/Library/Android/sdk")
    # Linux user install: ~/Android/Sdk
    elseif(DEFINED ENV{HOME} AND EXISTS "$ENV{HOME}/Android/Sdk")
        set(_SDK_DIR "$ENV{HOME}/Android/Sdk")
    # Linux devcontainer / CI
    elseif(EXISTS "/opt/android/sdk")
        set(_SDK_DIR "/opt/android/sdk")
    endif()
endif()

# Normalise any backslashes introduced by Windows env-var expansion.
_awen_normalise_path(_SDK_DIR)

# ── 3. Derive NDK path from SDK if not explicitly set ────────────────────────
if(NOT _NDK_HOME AND _SDK_DIR)
    set(_NDK_HOME "${_SDK_DIR}/ndk/${_AWEN_NDK_VERSION}")
endif()

# 3b. Fall back to ANDROID_NDK_HOME env var
if(NOT _NDK_HOME)
    set(_NDK_HOME "$ENV{ANDROID_NDK_HOME}")
endif()

_awen_normalise_path(_NDK_HOME)

if(NOT _NDK_HOME OR NOT EXISTS "${_NDK_HOME}")
    message(FATAL_ERROR
        "Android NDK ${_AWEN_NDK_VERSION} not found.\n"
        "Install it via Android Studio SDK Manager, or set ANDROID_HOME / "
        "ANDROID_NDK_HOME, or add sdk.dir / ndk.dir to android/local.properties.")
endif()

# ── 4. Generate local.properties if missing or sdk.dir was absent ────────────
# Always (re)write so that the file uses forward slashes, which Java's
# Properties.load() requires on Windows (backslashes are escape chars there).
if(_SDK_DIR)
    message(STATUS "Writing android/local.properties (sdk.dir=${_SDK_DIR})")
    file(WRITE "${_LOCAL_PROPS}"
        "# Generated by CMake — do not commit this file.\n"
        "sdk.dir=${_SDK_DIR}\n"
    )
endif()

# ── 5. Set VCPKG_CHAINLOAD_TOOLCHAIN_FILE ────────────────────────────────────
if(NOT DEFINED VCPKG_CHAINLOAD_TOOLCHAIN_FILE OR VCPKG_CHAINLOAD_TOOLCHAIN_FILE STREQUAL "")
    set(VCPKG_CHAINLOAD_TOOLCHAIN_FILE
        "${_NDK_HOME}/build/cmake/android.toolchain.cmake"
        CACHE STRING "Android NDK CMake toolchain" FORCE)
    message(STATUS "Android NDK: ${_NDK_HOME}")
endif()

include("${CMAKE_CURRENT_LIST_DIR}/../../vcpkg/scripts/buildsystems/vcpkg.cmake")
