name: wasm

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docker:
    runs-on: ubuntu-24.04

    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write

    outputs:
      image: ${{ steps.docker-image.outputs.image }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/docker-image
        id: docker-image
        with:
          platform: wasm
          token: ${{ secrets.GITHUB_TOKEN }}

  build:
    runs-on: ubuntu-24.04
    needs: docker

    strategy:
      matrix:
        include:
          - preset: x64-linux-wasm-release
            target: install

    container:
      image: ${{ needs.docker.outputs.image }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: ./.github/actions/get-vcpkg

      - name: cmake-configure
        shell: bash
        run: cmake --preset ${{ matrix.preset }}

      - name: cmake-build
        shell: bash
        run: cmake --build --preset ${{ matrix.preset }} --parallel $(( $(nproc --all) + 1 ))

      - name: cmake-${{ matrix.target }}
        shell: bash
        run: cmake --build --preset ${{ matrix.preset }} --target ${{ matrix.target }}
